[project]
name = "kaira-yes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.13.2",
    "aiohttp-cors>=0.8.1",
    "aiortc>=1.14.0",
    "av>=16.0.1",
    "dlib>=20.0.0",
    "fastapi>=0.121.2",
    "google-genai>=1.50.1",
    "noisereduce>=3.0.3",
    "numpy>=2.3.4",
    "opencv-python>=4.11.0.86",
    "openpyxl>=3.1.5",
    "openwakeword>=0.4.0",
    "pandas>=2.3.3",
    "pillow>=12.0.0",
    "pyaudio>=0.2.14",
    "pygame>=2.6.1",
    "pyqt6-webengine>=6.10.0",
    "python-dotenv>=1.2.1",
    "pyzmq>=27.1.0",
    "qrcode>=8.2",
    "realtimestt>=0.3.104",
    "requests>=2.32.5",
    "sentence-transformers>=5.1.2",
    "thefuzz>=0.22.1",
    "torch>=2.9.1",
    "uvicorn>=0.38.0",
]
